/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JPA_Project;

import java.util.Arrays;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;


public class App {
       public static void main(String[] args) {
//        System.out.println("Hello World");
    	   
    	   
    	   //in JPA we have to configure EntityManagerFectory and EntityManager 
    	   EntityManagerFactory emf = Persistence.createEntityManagerFactory("people_details");
    	   EntityManager em = emf.createEntityManager();
    	   
    	   //begin transaction
    	   em.getTransaction().begin();
    	   
    	   //work
    	   
//    	   insertion 
    	   
    	   //mobile data
    	   Mobile m1 = new Mobile();
    	   m1.setM_id(101);
    	   m1.setM_name("Vivo");
    	   
    	   Mobile m2 = new Mobile();
    	   m2.setM_id(202);
    	   m2.setM_name("iPhone");
    	   
    	   Mobile m3 = new Mobile();
    	   m3.setM_id(303);
    	   m3.setM_name("Samsung");
    	   
    	   //people data
    	   People p1 = new People();
    	   p1.setP_ID(1);
    	   p1.setP_name("Jaydeep");    	   
    	   
    	   People p2 = new People();
    	   p2.setP_ID(2);
    	   p2.setP_name("Jack");
    	   
    	   People p3 = new People();
    	   p3.setP_ID(3);
    	   p3.setP_name("Ladva");
    	   
    	   //Books data
    	   Books b1 = new Books();
    	   b1.setB_no(11011);
    	   b1.setB_name("OOP with Java");
    	   
    	   Books b2 = new Books();
    	   b2.setB_no(12021);
    	   b2.setB_name("IOT");
    	   
    	   Books b3 = new Books();
    	   b3.setB_no(13031);
    	   b3.setB_name("Object Fundamentals");
    	   
    	   Laptop laptop1 = new Laptop();
       		laptop1.setL_id(1111);
       		laptop1.setL_name("Dell");
       	
	       	Laptop laptop2 = new Laptop();
	       	laptop2.setL_id(2222);
	       	laptop2.setL_name("HP");
	       	
	       	Laptop laptop3 = new Laptop();
	       	laptop3.setL_id(3333);
	       	laptop3.setL_name("lenovo");
    	   
    	   List<Books> bks = Arrays.asList(b1,b2,b3);
    	   List<Laptop> lps = Arrays.asList(laptop1,laptop2,laptop3);
    	   List<People> ppl = Arrays.asList(p1,p2,p3);
    	   
    	   p1.setMobile(m1);
    	   m1.setPeople(p1);
    	   p1.setBooks(bks);
    	   p1.setLaptop(lps);
    	   laptop1.setPeople(ppl);
    	   
    	   p2.setMobile(m2);
    	   m2.setPeople(p2);
    	   p2.setLaptop(lps);
    	   laptop2.setPeople(ppl);
    	   
    	   p3.setMobile(m3);
    	   m3.setPeople(p3);
    	   p3.setLaptop(lps);
    	   laptop3.setPeople(ppl);
    	   
    	   b1.setPeople(p1);
    	   b2.setPeople(p1);
    	   b3.setPeople(p1);
    	   
    	   //for saving data in JPA 
    	   em.persist(p1);
//    	   em.persist(m1);
//    	   em.persist(b1);
    	   
    	   em.persist(p2);
//    	   em.persist(m2);
//    	   em.persist(b2);
    	   
    	   em.persist(p3);
//    	   em.persist(m3);
//    	   em.persist(b3);
    	   
//    	   //find operation
    	  // People pf = em.find(People.class, 1);
//    	   System.out.println(pf.toString());
    	 
//    	   //update operation
//    	   pf.setP_name("Jaydeep Ladva");
//    	   System.out.println(pf.toString());
    	   
    	   //delete data operation
//    	   em.remove(pf);
    	   
    	   
    	   //Query
    	   
    	   Query query = em.createQuery("from People");
    	   
    	   List<People> nams = query.getResultList();
    	   nams.forEach(System.out::println);
    	   
    	  
    	   
    	   em.getTransaction().commit();
    	   
    	   em.close();
    	   emf.close();
    	   
    	   
    	   
    	   
    }
}
