/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App1;

import java.util.Arrays;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

public class App {
	public static void main(String[] args) {
		
	
		Names n1 = new Names();
		n1.setFirst_name("Jaydeep");
		n1.setLast_name("Ladva");
		
		Books books = new Books();
		books.setB_id(101);
		books.setB_name("OOP with Java");
		
		Student student = new Student();
		student.setSid(1);
		student.setNames(n1);
		student.setMarks(99);
		
		Laptop l1 = new Laptop();
		l1.setI_name("Dell");
		l1.setL_id(1011);
		l1.setStudent(student);
		
		Laptop l2 = new Laptop();
		l2.setI_name("HP");
		l2.setL_id(2011);
		l2.setStudent(student);
		
		Laptop l3 = new Laptop();
		l3.setI_name("Lenovo");
		l3.setL_id(3011);
		l3.setStudent(student);
		
		List<Laptop> lps = Arrays.asList(l1,l2,l3);
		
		student.setBooks(books);
		student.setLaptop(lps);
		books.setStudent(student);
		
		
		//first configure 
		Configuration con = new Configuration().configure("hibernate.cfg.xml").addAnnotatedClass(Student.class).addAnnotatedClass(Books.class)
				.addAnnotatedClass(Laptop.class);
		// There is no need to annotate Embeddable class 
		//		.addAnnotatedClass(Names.class);
		//create session fectory
		SessionFactory sf = con.buildSessionFactory();
		
		// open session
		Session s1 = sf.openSession();
		//begin transaction
		Transaction tx = s1.beginTransaction();
		//save stuff
		s1.save(student);
		s1.save(l1);
		s1.save(l2);
		s1.save(l3);
		s1.save(books);
		
//		Student st = s1.get(Student.class, 1);
//		System.out.println(st);
	
		
		
		
		tx.commit();
		s1.close();
		
		
		
	}
}
