/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JPA_Inheritance;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class App {

    public static void main(String[] args) {
      
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("employee_details");
    	EntityManager em = emf.createEntityManager();
    	
    	em.getTransaction().begin();
    	
    	ActiveEmployee ae1 = new ActiveEmployee(101,"Jaydeep",100000,4);
    	ActiveEmployee ae2 = new ActiveEmployee(102,"Jack",10000,3);
    	
    	RetiredEmployee re1 = new RetiredEmployee(103,"Ladva",5000);
    	RetiredEmployee re2 = new RetiredEmployee(104,"Ladvaaaaa",7000);
    	
    	
    	em.persist(ae1);
    	em.persist(ae2);
    	em.persist(re1);
    	em.persist(re2);
    	
    	
    	
    	
    	em.getTransaction().commit();
    	em.close();
    	emf.close();
    	
    }
}
