/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App1;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

public class App {
	public static void main(String[] args) {
		System.out.println("Hello world");
		
		Names n1 = new Names();
		n1.setFirst_name("Jaydeep");
		n1.setLast_name("Ladva");
		
		Student student = new Student();
		student.setSid(1);
		student.setNames(n1);
		student.setMarks(99);
		
		
		Configuration con = new Configuration().configure("hibernate.cfg.xml").addAnnotatedClass(Student.class);
		// There is no need to annotate Embeddable class 
		//		.addAnnotatedClass(Names.class);
		
		SessionFactory sf = con.buildSessionFactory();
		
		
		Session s1 = sf.openSession();
		Transaction tx = s1.beginTransaction();
		
		s1.save(student);
		Student s2 = s1.get(Student.class,1);
		System.out.println(s2);
		
		tx.commit();
		s1.close();
		
		
		
	}
}
